name: Nix (Build+Test)

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: DeterminateSystems/nix-installer-action@main

    # not needed (yet)
    # - uses: cachix/cachix-action@v12
    #   with:
    #     name: hyprland
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: cachix/cachix-action@v15
      with:
        name: hyprland
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: Build
      run: nix build .#hyprlock --print-build-logs --keep-going

    - name: Test (Run on Hyprland)
      run: nix flake check --print-build-logs --keep-going

